### ISSUE TITLE
ctl-lists big query datset is not awailable

### ISSUE THREAD

**Issue by necipkafadar** [pentester-io/commonspeak#3]
Hi,
It seems that Certificate Transparency Logs("ctl-lists:ctl_data.cert_data" in the tool) dateset in Big Query is not available for public access anymore. It gives this error message when a query is executed `"Error: Access Denied: Table ctl-lists:ctl_data.cert_data: The user <user name> does not have permission to query table ctl-lists:ctl_data.cert_data."`

**Comment by infosec-au** [comment]
Hi @necipkafadar -

In order to get access to this dataset, you'll need to contact Ryan Sears from CaliDog security `ryan@calidog.io`.

I've stated this at the end of my blog, and you can find more details about the dataset by reading this:

https://medium.com/cali-dog-security/retrieving-storing-and-querying-250m-certificates-like-a-boss-31b1ce2dfcf8
